import { Layout } from "@/ui/components/layout/Layout";
import { Seo } from "@/ui/components/seo/Seo";
import { LandingPageContainer } from "@/ui/modules/landing-page/landing-page.container";

export default function Home() {
  return (
    <>
      <Seo
        title="Mon portfolio"
        description="This portfolio generated by create next app"
      ></Seo>

      <Layout>
        <LandingPageContainer />
      </Layout>
    </>
  );
}
