import { ToggleNavProvider } from "@/context/ToggleNavContext";
import { DarkModeProvider } from "@/ui/components/darkMode/DarkModeGlobal";
import { Layout } from "@/ui/components/layout/Layout";
import { Seo } from "@/ui/components/seo/Seo";
import { LandingPageContainer } from "@/ui/modules/landing-page/landing-page.container";

export default function Home() {
  return (
    <>
      <Seo
        title="Portfolio-Brondone"
        description="This portfolio generated by create next app"
      ></Seo>
      <DarkModeProvider>
        <ToggleNavProvider>
          <Layout>
            <LandingPageContainer />
          </Layout>
        </ToggleNavProvider>
      </DarkModeProvider>
    </>
  );
}
